/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksIdRouteImport } from './routes/webhooks.$id'
import { Route as EndpointsSlugRouteImport } from './routes/endpoints.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksIdRoute = WebhooksIdRouteImport.update({
  id: '/webhooks/$id',
  path: '/webhooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsSlugRoute = EndpointsSlugRouteImport.update({
  id: '/endpoints/$slug',
  path: '/endpoints/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/endpoints/$slug': typeof EndpointsSlugRoute
  '/webhooks/$id': typeof WebhooksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/endpoints/$slug': typeof EndpointsSlugRoute
  '/webhooks/$id': typeof WebhooksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/endpoints/$slug': typeof EndpointsSlugRoute
  '/webhooks/$id': typeof WebhooksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/endpoints/$slug' | '/webhooks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/endpoints/$slug' | '/webhooks/$id'
  id: '__root__' | '/' | '/endpoints/$slug' | '/webhooks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndpointsSlugRoute: typeof EndpointsSlugRoute
  WebhooksIdRoute: typeof WebhooksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/$id': {
      id: '/webhooks/$id'
      path: '/webhooks/$id'
      fullPath: '/webhooks/$id'
      preLoaderRoute: typeof WebhooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$slug': {
      id: '/endpoints/$slug'
      path: '/endpoints/$slug'
      fullPath: '/endpoints/$slug'
      preLoaderRoute: typeof EndpointsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndpointsSlugRoute: EndpointsSlugRoute,
  WebhooksIdRoute: WebhooksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
